name:                hask-enigma
version:             0.1.0.0
github:              "githubuser/hask-enigma"
license:             BSD3
author:              Welperooni
maintainer:          "Welperooni@gmail.com"
copyright:           "2018 Welperooni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Welperooni/hask-enigma#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - vector
    - containers

executables:
  hask-enigma-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-enigma
    - vector
    - containers

tests:
  hask-enigma-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-enigma
